#!/bin/bash

USAR_ISO_RED=0
BINARIO=/tmp/kernel32-3.0.4
ISO=/tmp/Fedora14-x86-root_fs
MEM=1024m

if [ $# -eq 3 ]; then
	BINARIO=$1
	ISO=$2
	MEM=$3
elif [ $# -eq 2 ]; then
	BINARIO=$1
	ISO=$2
elif [ $# -eq 1 ]; then
	if [ $1 -eq 1 ]; then
		USAR_ISO_RED=1
	fi

fi


if [[ USAR_ISO_RED -eq 0 ]]; then
	if [ ! -e $BINARIO ]; then
		echo "Usando PATH por defecto."
		cp /fenix/depar/lsi/UML/kernel32-3.0.4.gz /tmp/
		gunzip /tmp/kernel32-3.0.4.gz
	fi

	if [ ! -e $ISO ]; then
			echo "Usando ISO por defecto.";
			cp /fenix/depar/lsi/UML/Fedora14-x86-root_fs.gz /tmp/
			gunzip /tmp/Fedora14-x86-root_fs.gz
	fi
else
	if [ ! -e /tmp/Fedora14 ]; then
		wget http://fs.devloop.org.uk/filesystems/Fedora14/Fedora14-x86-root_fs.bz2 -O /tmp/Fedora14.bz2
		bzip2 -d /tmp/Fedora14.bz2
	fi
	
	if [ ! -e /tmp/kernel ]; then
		wget http://uml.devloop.org.uk/kernels/kernel32-3.0.101.xz -O /tmp/kernel.xz
		xz --decompress /tmp/kernel.xz
	fi

	chmod +x /tmp/kernel

	BINARIO=/tmp/kernel
	ISO=/tmp/Fedora14

fi

$BINARIO ubda=$ISO mem=$MEM 